export const TeamPageModule = {
    state: {
        isSortDescending: true,
        sortOption: '',
        searchQuery: '',
        searchField: '',
        isAddUser: false,
        isEditUser: false,
        editedUser: '',
        users: [
            {
                id: 1,
                name: 'Sarah Connor',
                team: 'Crosty',
                role: 'Team Lead',
                gmail: 'sarahconnor@gmail.com',
                birthday: '25.04.1994',
                age: 28,
                telegram: '@sarahconnor',
                lastLogin: '03.11.2021',
                isOnline: true,
                gender: 'female',
                hireDate: '01.02.2023',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 2,
                name: 'Ernest Eberly',
                team: 'Flamethrower',
                role: 'Semantic Specialist',
                gmail: 'ernesteberly@gmail.com',
                birthday: '25.04.1994',
                age: 23,
                telegram: '@ErnestEberly',
                lastLogin: '03.11.2021',
                isOnline: false,
                gender: 'male',
                hireDate: '12.02.2020',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 3,
                name: 'Arnold Brown',
                team: 'Gunters',
                role: 'Seo Specialist',
                gmail: 'arnoldbrown@gmail.com',
                birthday: '12.04.1989',
                age: 31,
                telegram: '@arnoldbrown',
                lastLogin: '02.11.2021',
                isOnline: true,
                gender: 'male',
                hireDate: '01.08.2020',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            { 
                'id': 4, 
                'name': 'John Smith', 
                'team': 'Tech Wizards', 
                'role': 'Frontend Developer', 
                'gmail': 'johnsmith@gmail.com', 
                'birthday': '15.09.1992', 
                'age': 28, 
                'telegram': '@johnsmithdev', 
                'lastLogin': '10.03.2023', 
                'isOnline': true, 
                'gender': 'male', 
                'hireDate': '05.06.2021', 
                'avatar': 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png' 
            }, 
            { 
                'id': 5, 
                'name': 'Emily Johnson', 
                'team': 'Pixel Crafters', 
                'role': 'UI/UX Designer', 
                'gmail': 'emilyjohnson@gmail.com', 
                'birthday': '03.07.1990', 
                'age': 34, 'telegram': '@emilydesigns', 
                'lastLogin': '18.02.2023', 
                'isOnline': true, 
                'gender': 'female', 
                'hireDate': '20.11.2019', 
                'avatar': 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png' 
            }, 
            { 
                'id': 6, 
                'name': 'Daniel Lee', 
                'team': 'Code Ninjas', 
                'role': 'Backend Developer', 
                'gmail': 'daniellee@gmail.com', 
                'birthday': '28.05.1987', 
                'age': 37, 
                'telegram': '@danielleecode', 
                'lastLogin': '05.01.2023', 
                'isOnline': true, 
                'gender': 'male', 
                'hireDate': '15.09.2018', 
                'avatar': 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png' 
            }, 
            { 
                'id': 7, 
                'name': 'Sophia Rodriguez', 
                'team': 'Creative Minds', 
                'role': 'Graphic Designer', 
                'gmail': 'sophiarodriguez@gmail.com', 
                'birthday': '10.12.1995', 
                'age': 29, 
                'telegram': '@sophiacreatives', 
                'lastLogin': '30.04.2023', 
                'isOnline': true, 
                'gender': 'female', 
                'hireDate': '02.03.2020', 
                'avatar': 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png' 
            }, 
            { 
                'id': 8, 
                'name': 'Oliver White', 
                'team': 'Data Wizards', 
                'role': 'Data Analyst', 
                'gmail': 'oliverwhite@gmail.com', 
                'birthday': '22.11.1985', 
                'age': 39, 
                'telegram': '@oliverdata', 
                'lastLogin': '12.08.2023', 
                'isOnline': true, 
                'gender': 'male', 
                'hireDate': '10.05.2017', 
                'avatar': 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png' 
            }, 
            { 
                'id': 9, 
                'name': 
                'Isabella Martin', 
                'team': 'Marketing Gurus', 
                'role': 'Digital Marketer', 
                'gmail': 'isabellamartin@gmail.com', 
                'birthday': '18.01.1998', 
                'age': 26, 
                'telegram': '@isabellamarketing', 
                'lastLogin': '25.07.2023', 
                'isOnline': true, 
                'gender': 'female', 
                'hireDate': '08.04.2019', 
                'avatar': 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png' 
            }, 
            { 
                'id': 10, 
                'name': 'William Turner', 
                'team': 'Tech Innovators', 
                'role': 'Software Engineer', 
                'gmail': 'williamturner@gmail.com', 
                'birthday': '05.03.1993', 
                'age': 31, 
                'telegram': '@williamengineer', 
                'lastLogin': '20.09.2023', 
                'isOnline': true, 
                'gender': 'male', 
                'hireDate': '14.07.2021', 
                'avatar': 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png' 
            },
            
            {
                id: 11,
                name: 'Alice Smith',
                team: 'Gunters',
                role: 'UI/UX Designer',
                gmail: 'alicesmith@gmail.com',
                birthday: '25.09.1992',
                age: 28,
                telegram: '@alicesmith',
                lastLogin: '15.03.2022',
                isOnline: false,
                gender: 'female',
                hireDate: '10.06.2021',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 12,
                name: 'Bob Johnson',
                team: 'Gunters',
                role: 'Frontend Developer',
                gmail: 'bobjohnson@gmail.com',
                birthday: '18.07.1985',
                age: 35,
                telegram: '@bobjohnson',
                lastLogin: '22.02.2022',
                isOnline: true,
                gender: 'male',
                hireDate: '03.05.2019',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 13,
                name: 'Charlie Wilson',
                team: 'Gunters',
                role: 'Backend Developer',
                gmail: 'charliewilson@gmail.com',
                birthday: '05.11.1990',
                age: 30,
                telegram: '@charliewilson',
                lastLogin: '19.01.2022',
                isOnline: false,
                gender: 'male',
                hireDate: '28.03.2018',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 14,
                name: 'Eve Davis',
                team: 'Gunters',
                role: 'Project Manager',
                gmail: 'evedavis@gmail.com',
                birthday: '09.08.1987',
                age: 33,
                telegram: '@evedavis',
                lastLogin: '04.04.2022',
                isOnline: true,
                gender: 'female',
                hireDate: '22.10.2016',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 15,
                name: 'Frank Rodriguez',
                team: 'Gunters',
                role: 'QA Engineer',
                gmail: 'frankrodriguez@gmail.com',
                birthday: '17.01.1995',
                age: 25,
                telegram: '@frankrodriguez',
                lastLogin: '27.05.2022',
                isOnline: true,
                gender: 'male',
                hireDate: '14.12.2020',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 16,
                name: 'Grace Lee',
                team: 'Gunters',
                role: 'UI/UX Designer',
                gmail: 'gracelee@gmail.com',
                birthday: '23.06.1993',
                age: 27,
                telegram: '@gracelee',
                lastLogin: '08.09.2021',
                isOnline: false,
                gender: 'female',
                hireDate: '30.04.2019',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 17,
                name: 'Hank Garcia',
                team: 'Gunters',
                role: 'Backend Developer',
                gmail: 'hankgarcia@gmail.com',
                birthday: '12.03.1986',
                age: 34,
                telegram: '@hankgarcia',
                lastLogin: '10.07.2022',
                isOnline: false,
                gender: 'male',
                hireDate: '05.02.2018',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 18,
                name: 'Ivy Cooper',
                team: 'Gunters',
                role: 'Frontend Developer',
                gmail: 'ivycooper@gmail.com',
                birthday: '30.12.1991',
                age: 29,
                telegram: '@ivycooper',
                lastLogin: '23.11.2021',
                isOnline: true,
                gender: 'female',
                hireDate: '17.08.2017',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 19,
                name: 'Jack Thompson',
                team: 'Gunters',
                role: 'SEO Specialist',
                gmail: 'jackthompson@gmail.com',
                birthday: '14.05.1984',
                age: 36,
                telegram: '@jackthompson',
                lastLogin: '12.01.2022',
                isOnline: false,
                gender: 'male',
                hireDate: '09.04.2020',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 20,
                name: 'Kelly Ward',
                team: 'Gunters',
                role: 'Project Manager',
                gmail: 'kellyward@gmail.com',
                birthday: '03.09.1988',
                age: 32,
                telegram: '@kellyward',
                lastLogin: '30.06.2022',
                isOnline: true,
                gender: 'female',
                hireDate: '27.02.2016',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 21,
                name: 'Aaron White',
                team: 'Gunters',
                role: 'Content Writer',
                gmail: 'aaronwhite@gmail.com',
                birthday: '02.07.1993',
                age: 31,
                telegram: '@aaronwhite',
                lastLogin: '15.03.2022',
                isOnline: true,
                gender: 'male',
                hireDate: '10.06.2021',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 22,
                name: 'Bethany Green',
                team: 'Gunters',
                role: 'Graphic Designer',
                gmail: 'bethanygreen@gmail.com',
                birthday: '18.12.1985',
                age: 35,
                telegram: '@bethanygreen',
                lastLogin: '22.02.2022',
                isOnline: true,
                gender: 'female',
                hireDate: '03.05.2019',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 23,
                name: 'Cameron Brown',
                team: 'Gunters',
                role: 'Product Manager',
                gmail: 'cameronbrown@gmail.com',
                birthday: '05.06.1990',
                age: 30,
                telegram: '@cameronbrown',
                lastLogin: '19.01.2022',
                isOnline: false,
                gender: 'male',
                hireDate: '28.03.2018',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 24,
                name: 'Diana Reed',
                team: 'Gunters',
                role: 'Frontend Developer',
                gmail: 'dianareed@gmail.com',
                birthday: '09.03.1987',
                age: 33,
                telegram: '@dianareed',
                lastLogin: '04.04.2022',
                isOnline: true,
                gender: 'female',
                hireDate: '22.10.2016',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 25,
                name: 'Ethan King',
                team: 'Gunters',
                role: 'QA Engineer',
                gmail: 'ethanking@gmail.com',
                birthday: '17.08.1995',
                age: 25,
                telegram: '@ethanking',
                lastLogin: '27.05.2022',
                isOnline: true,
                gender: 'male',
                hireDate: '14.12.2020',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 26,
                name: 'Fiona Hill',
                team: 'Gunters',
                role: 'UI/UX Designer',
                gmail: 'fionahill@gmail.com',
                birthday: '23.02.1993',
                age: 27,
                telegram: '@fionahill',
                lastLogin: '08.09.2021',
                isOnline: false,
                gender: 'female',
                hireDate: '30.04.2019',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 27,
                name: 'George Clark',
                team: 'Gunters',
                role: 'Backend Developer',
                gmail: 'georgeclark@gmail.com',
                birthday: '12.11.1986',
                age: 34,
                telegram: '@georgeclark',
                lastLogin: '10.07.2022',
                isOnline: false,
                gender: 'male',
                hireDate: '05.02.2018',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 28,
                name: 'Hannah Baker',
                team: 'Gunters',
                role: 'Frontend Developer',
                gmail: 'hannahbaker@gmail.com',
                birthday: '30.04.1991',
                age: 29,
                telegram: '@hannahbaker',
                lastLogin: '23.11.2021',
                isOnline: true,
                gender: 'female',
                hireDate: '17.08.2017',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 29,
                name: 'Ian Miller',
                team: 'Gunters',
                role: 'SEO Specialist',
                gmail: 'ianmiller@gmail.com',
                birthday: '14.09.1984',
                age: 36,
                telegram: '@ianmiller',
                lastLogin: '12.01.2022',
                isOnline: false,
                gender: 'male',
                hireDate: '09.04.2020',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 30,
                name: 'Jasmine Reed',
                team: 'Gunters',
                role: 'Project Manager',
                gmail: 'jasminereed@gmail.com',
                birthday: '03.02.1988',
                age: 32,
                telegram: '@jasminereed',
                lastLogin: '30.06.2022',
                isOnline: true,
                gender: 'female',
                hireDate: '27.02.2016',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 31,
                name: 'Sarah Connor',
                team: 'Crosty',
                role: 'Team Lead',
                gmail: 'sarahconnor@gmail.com',
                birthday: '25.04.1994',
                age: 28,
                telegram: '@sarahconnor',
                lastLogin: '03.11.2021',
                isOnline: true,
                gender: 'female',
                hireDate: '01.02.2023',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 32,
                name: 'Ernest Eberly',
                team: 'Flamethrower',
                role: 'Semantic Specialist',
                gmail: 'ernesteberly@gmail.com',
                birthday: '25.04.1994',
                age: 23,
                telegram: '@ErnestEberly',
                lastLogin: '03.11.2021',
                isOnline: false,
                gender: 'male',
                hireDate: '12.02.2020',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 33,
                name: 'Arnold Brown',
                team: 'Gunters',
                role: 'Seo Specialist',
                gmail: 'arnoldbrown@gmail.com',
                birthday: '12.04.1989',
                age: 31,
                telegram: '@arnoldbrown',
                lastLogin: '02.11.2021',
                isOnline: true,
                gender: 'male',
                hireDate: '01.08.2020',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            { 
                'id': 34, 
                'name': 'John Smith', 
                'team': 'Tech Wizards', 
                'role': 'Frontend Developer', 
                'gmail': 'johnsmith@gmail.com', 
                'birthday': '15.09.1992', 
                'age': 28, 
                'telegram': '@johnsmithdev', 
                'lastLogin': '10.03.2023', 
                'isOnline': true, 
                'gender': 'male', 
                'hireDate': '05.06.2021', 
                'avatar': 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png' 
            }, 
            { 
                'id': 35, 
                'name': 'Emily Johnson', 
                'team': 'Pixel Crafters', 
                'role': 'UI/UX Designer', 
                'gmail': 'emilyjohnson@gmail.com', 
                'birthday': '03.07.1990', 
                'age': 34, 'telegram': '@emilydesigns', 
                'lastLogin': '18.02.2023', 
                'isOnline': true, 
                'gender': 'female', 
                'hireDate': '20.11.2019', 
                'avatar': 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png' 
            }, 
            { 
                'id': 36, 
                'name': 'Daniel Lee', 
                'team': 'Code Ninjas', 
                'role': 'Backend Developer', 
                'gmail': 'daniellee@gmail.com', 
                'birthday': '28.05.1987', 
                'age': 37, 
                'telegram': '@danielleecode', 
                'lastLogin': '05.01.2023', 
                'isOnline': true, 
                'gender': 'male', 
                'hireDate': '15.09.2018', 
                'avatar': 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png' 
            }, 
            { 
                'id': 37, 
                'name': 'Sophia Rodriguez', 
                'team': 'Creative Minds', 
                'role': 'Graphic Designer', 
                'gmail': 'sophiarodriguez@gmail.com', 
                'birthday': '10.12.1995', 
                'age': 29, 
                'telegram': '@sophiacreatives', 
                'lastLogin': '30.04.2023', 
                'isOnline': true, 
                'gender': 'female', 
                'hireDate': '02.03.2020', 
                'avatar': 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png' 
            }, 
            { 
                'id': 38, 
                'name': 'Oliver White', 
                'team': 'Data Wizards', 
                'role': 'Data Analyst', 
                'gmail': 'oliverwhite@gmail.com', 
                'birthday': '22.11.1985', 
                'age': 39, 
                'telegram': '@oliverdata', 
                'lastLogin': '12.08.2023', 
                'isOnline': true, 
                'gender': 'male', 
                'hireDate': '10.05.2017', 
                'avatar': 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png' 
            }, 
            { 
                'id': 39, 
                'name': 
                'Isabella Martin', 
                'team': 'Marketing Gurus', 
                'role': 'Digital Marketer', 
                'gmail': 'isabellamartin@gmail.com', 
                'birthday': '18.01.1998', 
                'age': 26, 
                'telegram': '@isabellamarketing', 
                'lastLogin': '25.07.2023', 
                'isOnline': true, 
                'gender': 'female', 
                'hireDate': '08.04.2019', 
                'avatar': 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png' 
            }, 
            { 
                'id': 40, 
                'name': 'William Turner', 
                'team': 'Tech Innovators', 
                'role': 'Software Engineer', 
                'gmail': 'williamturner@gmail.com', 
                'birthday': '05.03.1993', 
                'age': 31, 
                'telegram': '@williamengineer', 
                'lastLogin': '20.09.2023', 
                'isOnline': true, 
                'gender': 'male', 
                'hireDate': '14.07.2021', 
                'avatar': 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png' 
            },
            
            {
                id: 41,
                name: 'Alice Smith',
                team: 'Gunters',
                role: 'UI/UX Designer',
                gmail: 'alicesmith@gmail.com',
                birthday: '25.09.1992',
                age: 28,
                telegram: '@alicesmith',
                lastLogin: '15.03.2022',
                isOnline: false,
                gender: 'female',
                hireDate: '10.06.2021',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 42,
                name: 'Bob Johnson',
                team: 'Gunters',
                role: 'Frontend Developer',
                gmail: 'bobjohnson@gmail.com',
                birthday: '18.07.1985',
                age: 35,
                telegram: '@bobjohnson',
                lastLogin: '22.02.2022',
                isOnline: true,
                gender: 'male',
                hireDate: '03.05.2019',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 43,
                name: 'Charlie Wilson',
                team: 'Gunters',
                role: 'Backend Developer',
                gmail: 'charliewilson@gmail.com',
                birthday: '05.11.1990',
                age: 30,
                telegram: '@charliewilson',
                lastLogin: '19.01.2022',
                isOnline: false,
                gender: 'male',
                hireDate: '28.03.2018',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 44,
                name: 'Eve Davis',
                team: 'Gunters',
                role: 'Project Manager',
                gmail: 'evedavis@gmail.com',
                birthday: '09.08.1987',
                age: 33,
                telegram: '@evedavis',
                lastLogin: '04.04.2022',
                isOnline: true,
                gender: 'female',
                hireDate: '22.10.2016',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 45,
                name: 'Frank Rodriguez',
                team: 'Gunters',
                role: 'QA Engineer',
                gmail: 'frankrodriguez@gmail.com',
                birthday: '17.01.1995',
                age: 25,
                telegram: '@frankrodriguez',
                lastLogin: '27.05.2022',
                isOnline: true,
                gender: 'male',
                hireDate: '14.12.2020',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 46,
                name: 'Grace Lee',
                team: 'Gunters',
                role: 'UI/UX Designer',
                gmail: 'gracelee@gmail.com',
                birthday: '23.06.1993',
                age: 27,
                telegram: '@gracelee',
                lastLogin: '08.09.2021',
                isOnline: false,
                gender: 'female',
                hireDate: '30.04.2019',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 47,
                name: 'Hank Garcia',
                team: 'Gunters',
                role: 'Backend Developer',
                gmail: 'hankgarcia@gmail.com',
                birthday: '12.03.1986',
                age: 34,
                telegram: '@hankgarcia',
                lastLogin: '10.07.2022',
                isOnline: false,
                gender: 'male',
                hireDate: '05.02.2018',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 48,
                name: 'Ivy Cooper',
                team: 'Gunters',
                role: 'Frontend Developer',
                gmail: 'ivycooper@gmail.com',
                birthday: '30.12.1991',
                age: 29,
                telegram: '@ivycooper',
                lastLogin: '23.11.2021',
                isOnline: true,
                gender: 'female',
                hireDate: '17.08.2017',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 49,
                name: 'Jack Thompson',
                team: 'Gunters',
                role: 'SEO Specialist',
                gmail: 'jackthompson@gmail.com',
                birthday: '14.05.1984',
                age: 36,
                telegram: '@jackthompson',
                lastLogin: '12.01.2022',
                isOnline: false,
                gender: 'male',
                hireDate: '09.04.2020',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 50,
                name: 'Kelly Ward',
                team: 'Gunters',
                role: 'Project Manager',
                gmail: 'kellyward@gmail.com',
                birthday: '03.09.1988',
                age: 32,
                telegram: '@kellyward',
                lastLogin: '30.06.2022',
                isOnline: true,
                gender: 'female',
                hireDate: '27.02.2016',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 51,
                name: 'Aaron White',
                team: 'Gunters',
                role: 'Content Writer',
                gmail: 'aaronwhite@gmail.com',
                birthday: '02.07.1993',
                age: 31,
                telegram: '@aaronwhite',
                lastLogin: '15.03.2022',
                isOnline: true,
                gender: 'male',
                hireDate: '10.06.2021',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 52,
                name: 'Bethany Green',
                team: 'Gunters',
                role: 'Graphic Designer',
                gmail: 'bethanygreen@gmail.com',
                birthday: '18.12.1985',
                age: 35,
                telegram: '@bethanygreen',
                lastLogin: '22.02.2022',
                isOnline: true,
                gender: 'female',
                hireDate: '03.05.2019',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 53,
                name: 'Cameron Brown',
                team: 'Gunters',
                role: 'Product Manager',
                gmail: 'cameronbrown@gmail.com',
                birthday: '05.06.1990',
                age: 30,
                telegram: '@cameronbrown',
                lastLogin: '19.01.2022',
                isOnline: false,
                gender: 'male',
                hireDate: '28.03.2018',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 54,
                name: 'Diana Reed',
                team: 'Gunters',
                role: 'Frontend Developer',
                gmail: 'dianareed@gmail.com',
                birthday: '09.03.1987',
                age: 33,
                telegram: '@dianareed',
                lastLogin: '04.04.2022',
                isOnline: true,
                gender: 'female',
                hireDate: '22.10.2016',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 55,
                name: 'Ethan King',
                team: 'Gunters',
                role: 'QA Engineer',
                gmail: 'ethanking@gmail.com',
                birthday: '17.08.1995',
                age: 25,
                telegram: '@ethanking',
                lastLogin: '27.05.2022',
                isOnline: true,
                gender: 'male',
                hireDate: '14.12.2020',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 56,
                name: 'Fiona Hill',
                team: 'Gunters',
                role: 'UI/UX Designer',
                gmail: 'fionahill@gmail.com',
                birthday: '23.02.1993',
                age: 27,
                telegram: '@fionahill',
                lastLogin: '08.09.2021',
                isOnline: false,
                gender: 'female',
                hireDate: '30.04.2019',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 57,
                name: 'George Clark',
                team: 'Gunters',
                role: 'Backend Developer',
                gmail: 'georgeclark@gmail.com',
                birthday: '12.11.1986',
                age: 34,
                telegram: '@georgeclark',
                lastLogin: '10.07.2022',
                isOnline: false,
                gender: 'male',
                hireDate: '05.02.2018',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 58,
                name: 'Hannah Baker',
                team: 'Gunters',
                role: 'Frontend Developer',
                gmail: 'hannahbaker@gmail.com',
                birthday: '30.04.1991',
                age: 29,
                telegram: '@hannahbaker',
                lastLogin: '23.11.2021',
                isOnline: true,
                gender: 'female',
                hireDate: '17.08.2017',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 59,
                name: 'Ian Miller',
                team: 'Gunters',
                role: 'SEO Specialist',
                gmail: 'ianmiller@gmail.com',
                birthday: '14.09.1984',
                age: 36,
                telegram: '@ianmiller',
                lastLogin: '12.01.2022',
                isOnline: false,
                gender: 'male',
                hireDate: '09.04.2020',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 60,
                name: 'Jasmine Reed',
                team: 'Gunters',
                role: 'Project Manager',
                gmail: 'jasminereed@gmail.com',
                birthday: '03.02.1988',
                age: 32,
                telegram: '@jasminereed',
                lastLogin: '30.06.2022',
                isOnline: true,
                gender: 'female',
                hireDate: '27.02.2016',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 61,
                name: 'Sarah Connor',
                team: 'Crosty',
                role: 'Team Lead',
                gmail: 'sarahconnor@gmail.com',
                birthday: '25.04.1994',
                age: 28,
                telegram: '@sarahconnor',
                lastLogin: '03.11.2021',
                isOnline: true,
                gender: 'female',
                hireDate: '01.02.2023',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 62,
                name: 'Ernest Eberly',
                team: 'Flamethrower',
                role: 'Semantic Specialist',
                gmail: 'ernesteberly@gmail.com',
                birthday: '25.04.1994',
                age: 23,
                telegram: '@ErnestEberly',
                lastLogin: '03.11.2021',
                isOnline: false,
                gender: 'male',
                hireDate: '12.02.2020',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 63,
                name: 'Arnold Brown',
                team: 'Gunters',
                role: 'Seo Specialist',
                gmail: 'arnoldbrown@gmail.com',
                birthday: '12.04.1989',
                age: 31,
                telegram: '@arnoldbrown',
                lastLogin: '02.11.2021',
                isOnline: true,
                gender: 'male',
                hireDate: '01.08.2020',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            { 
                'id': 64, 
                'name': 'John Smith', 
                'team': 'Tech Wizards', 
                'role': 'Frontend Developer', 
                'gmail': 'johnsmith@gmail.com', 
                'birthday': '15.09.1992', 
                'age': 28, 
                'telegram': '@johnsmithdev', 
                'lastLogin': '10.03.2023', 
                'isOnline': true, 
                'gender': 'male', 
                'hireDate': '05.06.2021', 
                'avatar': 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png' 
            }, 
            { 
                'id': 65, 
                'name': 'Emily Johnson', 
                'team': 'Pixel Crafters', 
                'role': 'UI/UX Designer', 
                'gmail': 'emilyjohnson@gmail.com', 
                'birthday': '03.07.1990', 
                'age': 34, 'telegram': '@emilydesigns', 
                'lastLogin': '18.02.2023', 
                'isOnline': true, 
                'gender': 'female', 
                'hireDate': '20.11.2019', 
                'avatar': 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png' 
            }, 
            { 
                'id': 66, 
                'name': 'Daniel Lee', 
                'team': 'Code Ninjas', 
                'role': 'Backend Developer', 
                'gmail': 'daniellee@gmail.com', 
                'birthday': '28.05.1987', 
                'age': 37, 
                'telegram': '@danielleecode', 
                'lastLogin': '05.01.2023', 
                'isOnline': true, 
                'gender': 'male', 
                'hireDate': '15.09.2018', 
                'avatar': 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png' 
            }, 
            { 
                'id': 67, 
                'name': 'Sophia Rodriguez', 
                'team': 'Creative Minds', 
                'role': 'Graphic Designer', 
                'gmail': 'sophiarodriguez@gmail.com', 
                'birthday': '10.12.1995', 
                'age': 29, 
                'telegram': '@sophiacreatives', 
                'lastLogin': '30.04.2023', 
                'isOnline': true, 
                'gender': 'female', 
                'hireDate': '02.03.2020', 
                'avatar': 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png' 
            }, 
            { 
                'id': 68, 
                'name': 'Oliver White', 
                'team': 'Data Wizards', 
                'role': 'Data Analyst', 
                'gmail': 'oliverwhite@gmail.com', 
                'birthday': '22.11.1985', 
                'age': 39, 
                'telegram': '@oliverdata', 
                'lastLogin': '12.08.2023', 
                'isOnline': true, 
                'gender': 'male', 
                'hireDate': '10.05.2017', 
                'avatar': 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png' 
            }, 
            { 
                'id': 69, 
                'name': 
                'Isabella Martin', 
                'team': 'Marketing Gurus', 
                'role': 'Digital Marketer', 
                'gmail': 'isabellamartin@gmail.com', 
                'birthday': '18.01.1998', 
                'age': 26, 
                'telegram': '@isabellamarketing', 
                'lastLogin': '25.07.2023', 
                'isOnline': true, 
                'gender': 'female', 
                'hireDate': '08.04.2019', 
                'avatar': 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png' 
            }, 
            { 
                'id': 70, 
                'name': 'William Turner', 
                'team': 'Tech Innovators', 
                'role': 'Software Engineer', 
                'gmail': 'williamturner@gmail.com', 
                'birthday': '05.03.1993', 
                'age': 31, 
                'telegram': '@williamengineer', 
                'lastLogin': '20.09.2023', 
                'isOnline': true, 
                'gender': 'male', 
                'hireDate': '14.07.2021', 
                'avatar': 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png' 
            },
            
            {
                id: 71,
                name: 'Alice Smith',
                team: 'Gunters',
                role: 'UI/UX Designer',
                gmail: 'alicesmith@gmail.com',
                birthday: '25.09.1992',
                age: 28,
                telegram: '@alicesmith',
                lastLogin: '15.03.2022',
                isOnline: false,
                gender: 'female',
                hireDate: '10.06.2021',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 72,
                name: 'Bob Johnson',
                team: 'Gunters',
                role: 'Frontend Developer',
                gmail: 'bobjohnson@gmail.com',
                birthday: '18.07.1985',
                age: 35,
                telegram: '@bobjohnson',
                lastLogin: '22.02.2022',
                isOnline: true,
                gender: 'male',
                hireDate: '03.05.2019',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 73,
                name: 'Charlie Wilson',
                team: 'Gunters',
                role: 'Backend Developer',
                gmail: 'charliewilson@gmail.com',
                birthday: '05.11.1990',
                age: 30,
                telegram: '@charliewilson',
                lastLogin: '19.01.2022',
                isOnline: false,
                gender: 'male',
                hireDate: '28.03.2018',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 74,
                name: 'Eve Davis',
                team: 'Gunters',
                role: 'Project Manager',
                gmail: 'evedavis@gmail.com',
                birthday: '09.08.1987',
                age: 33,
                telegram: '@evedavis',
                lastLogin: '04.04.2022',
                isOnline: true,
                gender: 'female',
                hireDate: '22.10.2016',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 75,
                name: 'Frank Rodriguez',
                team: 'Gunters',
                role: 'QA Engineer',
                gmail: 'frankrodriguez@gmail.com',
                birthday: '17.01.1995',
                age: 25,
                telegram: '@frankrodriguez',
                lastLogin: '27.05.2022',
                isOnline: true,
                gender: 'male',
                hireDate: '14.12.2020',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 76,
                name: 'Grace Lee',
                team: 'Gunters',
                role: 'UI/UX Designer',
                gmail: 'gracelee@gmail.com',
                birthday: '23.06.1993',
                age: 27,
                telegram: '@gracelee',
                lastLogin: '08.09.2021',
                isOnline: false,
                gender: 'female',
                hireDate: '30.04.2019',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 77,
                name: 'Hank Garcia',
                team: 'Gunters',
                role: 'Backend Developer',
                gmail: 'hankgarcia@gmail.com',
                birthday: '12.03.1986',
                age: 34,
                telegram: '@hankgarcia',
                lastLogin: '10.07.2022',
                isOnline: false,
                gender: 'male',
                hireDate: '05.02.2018',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 78,
                name: 'Ivy Cooper',
                team: 'Gunters',
                role: 'Frontend Developer',
                gmail: 'ivycooper@gmail.com',
                birthday: '30.12.1991',
                age: 29,
                telegram: '@ivycooper',
                lastLogin: '23.11.2021',
                isOnline: true,
                gender: 'female',
                hireDate: '17.08.2017',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 79,
                name: 'Jack Thompson',
                team: 'Gunters',
                role: 'SEO Specialist',
                gmail: 'jackthompson@gmail.com',
                birthday: '14.05.1984',
                age: 36,
                telegram: '@jackthompson',
                lastLogin: '12.01.2022',
                isOnline: false,
                gender: 'male',
                hireDate: '09.04.2020',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 80,
                name: 'Kelly Ward',
                team: 'Gunters',
                role: 'Project Manager',
                gmail: 'kellyward@gmail.com',
                birthday: '03.09.1988',
                age: 32,
                telegram: '@kellyward',
                lastLogin: '30.06.2022',
                isOnline: true,
                gender: 'female',
                hireDate: '27.02.2016',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 81,
                name: 'Aaron White',
                team: 'Gunters',
                role: 'Content Writer',
                gmail: 'aaronwhite@gmail.com',
                birthday: '02.07.1993',
                age: 31,
                telegram: '@aaronwhite',
                lastLogin: '15.03.2022',
                isOnline: true,
                gender: 'male',
                hireDate: '10.06.2021',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 82,
                name: 'Bethany Green',
                team: 'Gunters',
                role: 'Graphic Designer',
                gmail: 'bethanygreen@gmail.com',
                birthday: '18.12.1985',
                age: 35,
                telegram: '@bethanygreen',
                lastLogin: '22.02.2022',
                isOnline: true,
                gender: 'female',
                hireDate: '03.05.2019',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 83,
                name: 'Cameron Brown',
                team: 'Gunters',
                role: 'Product Manager',
                gmail: 'cameronbrown@gmail.com',
                birthday: '05.06.1990',
                age: 30,
                telegram: '@cameronbrown',
                lastLogin: '19.01.2022',
                isOnline: false,
                gender: 'male',
                hireDate: '28.03.2018',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 84,
                name: 'Diana Reed',
                team: 'Gunters',
                role: 'Frontend Developer',
                gmail: 'dianareed@gmail.com',
                birthday: '09.03.1987',
                age: 33,
                telegram: '@dianareed',
                lastLogin: '04.04.2022',
                isOnline: true,
                gender: 'female',
                hireDate: '22.10.2016',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 85,
                name: 'Ethan King',
                team: 'Gunters',
                role: 'QA Engineer',
                gmail: 'ethanking@gmail.com',
                birthday: '17.08.1995',
                age: 25,
                telegram: '@ethanking',
                lastLogin: '27.05.2022',
                isOnline: true,
                gender: 'male',
                hireDate: '14.12.2020',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 86,
                name: 'Fiona Hill',
                team: 'Gunters',
                role: 'UI/UX Designer',
                gmail: 'fionahill@gmail.com',
                birthday: '23.02.1993',
                age: 27,
                telegram: '@fionahill',
                lastLogin: '08.09.2021',
                isOnline: false,
                gender: 'female',
                hireDate: '30.04.2019',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 87,
                name: 'George Clark',
                team: 'Gunters',
                role: 'Backend Developer',
                gmail: 'georgeclark@gmail.com',
                birthday: '12.11.1986',
                age: 34,
                telegram: '@georgeclark',
                lastLogin: '10.07.2022',
                isOnline: false,
                gender: 'male',
                hireDate: '05.02.2018',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 88,
                name: 'Hannah Baker',
                team: 'Gunters',
                role: 'Frontend Developer',
                gmail: 'hannahbaker@gmail.com',
                birthday: '30.04.1991',
                age: 29,
                telegram: '@hannahbaker',
                lastLogin: '23.11.2021',
                isOnline: true,
                gender: 'female',
                hireDate: '17.08.2017',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 89,
                name: 'Ian Miller',
                team: 'Gunters',
                role: 'SEO Specialist',
                gmail: 'ianmiller@gmail.com',
                birthday: '14.09.1984',
                age: 36,
                telegram: '@ianmiller',
                lastLogin: '12.01.2022',
                isOnline: false,
                gender: 'male',
                hireDate: '09.04.2020',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 90,
                name: 'Jasmine Reed',
                team: 'Gunters',
                role: 'Project Manager',
                gmail: 'jasminereed@gmail.com',
                birthday: '03.02.1988',
                age: 32,
                telegram: '@jasminereed',
                lastLogin: '30.06.2022',
                isOnline: true,
                gender: 'female',
                hireDate: '27.02.2016',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 91,
                name: 'Sarah Connor',
                team: 'Crosty',
                role: 'Team Lead',
                gmail: 'sarahconnor@gmail.com',
                birthday: '25.04.1994',
                age: 28,
                telegram: '@sarahconnor',
                lastLogin: '03.11.2021',
                isOnline: true,
                gender: 'female',
                hireDate: '01.02.2023',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 92,
                name: 'Ernest Eberly',
                team: 'Flamethrower',
                role: 'Semantic Specialist',
                gmail: 'ernesteberly@gmail.com',
                birthday: '25.04.1994',
                age: 23,
                telegram: '@ErnestEberly',
                lastLogin: '03.11.2021',
                isOnline: false,
                gender: 'male',
                hireDate: '12.02.2020',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 93,
                name: 'Arnold Brown',
                team: 'Gunters',
                role: 'Seo Specialist',
                gmail: 'arnoldbrown@gmail.com',
                birthday: '12.04.1989',
                age: 31,
                telegram: '@arnoldbrown',
                lastLogin: '02.11.2021',
                isOnline: true,
                gender: 'male',
                hireDate: '01.08.2020',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            { 
                'id': 94, 
                'name': 'John Smith', 
                'team': 'Tech Wizards', 
                'role': 'Frontend Developer', 
                'gmail': 'johnsmith@gmail.com', 
                'birthday': '15.09.1992', 
                'age': 28, 
                'telegram': '@johnsmithdev', 
                'lastLogin': '10.03.2023', 
                'isOnline': true, 
                'gender': 'male', 
                'hireDate': '05.06.2021', 
                'avatar': 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png' 
            }, 
            { 
                'id': 95, 
                'name': 'Emily Johnson', 
                'team': 'Pixel Crafters', 
                'role': 'UI/UX Designer', 
                'gmail': 'emilyjohnson@gmail.com', 
                'birthday': '03.07.1990', 
                'age': 34, 'telegram': '@emilydesigns', 
                'lastLogin': '18.02.2023', 
                'isOnline': true, 
                'gender': 'female', 
                'hireDate': '20.11.2019', 
                'avatar': 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png' 
            }, 
            { 
                'id': 96, 
                'name': 'Daniel Lee', 
                'team': 'Code Ninjas', 
                'role': 'Backend Developer', 
                'gmail': 'daniellee@gmail.com', 
                'birthday': '28.05.1987', 
                'age': 37, 
                'telegram': '@danielleecode', 
                'lastLogin': '05.01.2023', 
                'isOnline': true, 
                'gender': 'male', 
                'hireDate': '15.09.2018', 
                'avatar': 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png' 
            }, 
            { 
                'id': 97, 
                'name': 'Sophia Rodriguez', 
                'team': 'Creative Minds', 
                'role': 'Graphic Designer', 
                'gmail': 'sophiarodriguez@gmail.com', 
                'birthday': '10.12.1995', 
                'age': 29, 
                'telegram': '@sophiacreatives', 
                'lastLogin': '30.04.2023', 
                'isOnline': true, 
                'gender': 'female', 
                'hireDate': '02.03.2020', 
                'avatar': 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png' 
            }, 
            { 
                'id': 98, 
                'name': 'Oliver White', 
                'team': 'Data Wizards', 
                'role': 'Data Analyst', 
                'gmail': 'oliverwhite@gmail.com', 
                'birthday': '22.11.1985', 
                'age': 39, 
                'telegram': '@oliverdata', 
                'lastLogin': '12.08.2023', 
                'isOnline': true, 
                'gender': 'male', 
                'hireDate': '10.05.2017', 
                'avatar': 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png' 
            }, 
            { 
                'id': 99, 
                'name': 
                'Isabella Martin', 
                'team': 'Marketing Gurus', 
                'role': 'Digital Marketer', 
                'gmail': 'isabellamartin@gmail.com', 
                'birthday': '18.01.1998', 
                'age': 26, 
                'telegram': '@isabellamarketing', 
                'lastLogin': '25.07.2023', 
                'isOnline': true, 
                'gender': 'female', 
                'hireDate': '08.04.2019', 
                'avatar': 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png' 
            }, 
            { 
                'id': 100, 
                'name': 'William Turner', 
                'team': 'Tech Innovators', 
                'role': 'Software Engineer', 
                'gmail': 'williamturner@gmail.com', 
                'birthday': '05.03.1993', 
                'age': 31, 
                'telegram': '@williamengineer', 
                'lastLogin': '20.09.2023', 
                'isOnline': true, 
                'gender': 'male', 
                'hireDate': '14.07.2021', 
                'avatar': 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png' 
            },
            
            {
                id: 101,
                name: 'Alice Smith',
                team: 'Gunters',
                role: 'UI/UX Designer',
                gmail: 'alicesmith@gmail.com',
                birthday: '25.09.1992',
                age: 28,
                telegram: '@alicesmith',
                lastLogin: '15.03.2022',
                isOnline: false,
                gender: 'female',
                hireDate: '10.06.2021',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 102,
                name: 'Bob Johnson',
                team: 'Gunters',
                role: 'Frontend Developer',
                gmail: 'bobjohnson@gmail.com',
                birthday: '18.07.1985',
                age: 35,
                telegram: '@bobjohnson',
                lastLogin: '22.02.2022',
                isOnline: true,
                gender: 'male',
                hireDate: '03.05.2019',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 103,
                name: 'Charlie Wilson',
                team: 'Gunters',
                role: 'Backend Developer',
                gmail: 'charliewilson@gmail.com',
                birthday: '05.11.1990',
                age: 30,
                telegram: '@charliewilson',
                lastLogin: '19.01.2022',
                isOnline: false,
                gender: 'male',
                hireDate: '28.03.2018',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 104,
                name: 'Eve Davis',
                team: 'Gunters',
                role: 'Project Manager',
                gmail: 'evedavis@gmail.com',
                birthday: '09.08.1987',
                age: 33,
                telegram: '@evedavis',
                lastLogin: '04.04.2022',
                isOnline: true,
                gender: 'female',
                hireDate: '22.10.2016',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 105,
                name: 'Frank Rodriguez',
                team: 'Gunters',
                role: 'QA Engineer',
                gmail: 'frankrodriguez@gmail.com',
                birthday: '17.01.1995',
                age: 25,
                telegram: '@frankrodriguez',
                lastLogin: '27.05.2022',
                isOnline: true,
                gender: 'male',
                hireDate: '14.12.2020',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 106,
                name: 'Grace Lee',
                team: 'Gunters',
                role: 'UI/UX Designer',
                gmail: 'gracelee@gmail.com',
                birthday: '23.06.1993',
                age: 27,
                telegram: '@gracelee',
                lastLogin: '08.09.2021',
                isOnline: false,
                gender: 'female',
                hireDate: '30.04.2019',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 107,
                name: 'Hank Garcia',
                team: 'Gunters',
                role: 'Backend Developer',
                gmail: 'hankgarcia@gmail.com',
                birthday: '12.03.1986',
                age: 34,
                telegram: '@hankgarcia',
                lastLogin: '10.07.2022',
                isOnline: false,
                gender: 'male',
                hireDate: '05.02.2018',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 108,
                name: 'Ivy Cooper',
                team: 'Gunters',
                role: 'Frontend Developer',
                gmail: 'ivycooper@gmail.com',
                birthday: '30.12.1991',
                age: 29,
                telegram: '@ivycooper',
                lastLogin: '23.11.2021',
                isOnline: true,
                gender: 'female',
                hireDate: '17.08.2017',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 109,
                name: 'Jack Thompson',
                team: 'Gunters',
                role: 'SEO Specialist',
                gmail: 'jackthompson@gmail.com',
                birthday: '14.05.1984',
                age: 36,
                telegram: '@jackthompson',
                lastLogin: '12.01.2022',
                isOnline: false,
                gender: 'male',
                hireDate: '09.04.2020',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 110,
                name: 'Kelly Ward',
                team: 'Gunters',
                role: 'Project Manager',
                gmail: 'kellyward@gmail.com',
                birthday: '03.09.1988',
                age: 32,
                telegram: '@kellyward',
                lastLogin: '30.06.2022',
                isOnline: true,
                gender: 'female',
                hireDate: '27.02.2016',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 111,
                name: 'Aaron White',
                team: 'Gunters',
                role: 'Content Writer',
                gmail: 'aaronwhite@gmail.com',
                birthday: '02.07.1993',
                age: 31,
                telegram: '@aaronwhite',
                lastLogin: '15.03.2022',
                isOnline: true,
                gender: 'male',
                hireDate: '10.06.2021',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 112,
                name: 'Bethany Green',
                team: 'Gunters',
                role: 'Graphic Designer',
                gmail: 'bethanygreen@gmail.com',
                birthday: '18.12.1985',
                age: 35,
                telegram: '@bethanygreen',
                lastLogin: '22.02.2022',
                isOnline: true,
                gender: 'female',
                hireDate: '03.05.2019',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 113,
                name: 'Cameron Brown',
                team: 'Gunters',
                role: 'Product Manager',
                gmail: 'cameronbrown@gmail.com',
                birthday: '05.06.1990',
                age: 30,
                telegram: '@cameronbrown',
                lastLogin: '19.01.2022',
                isOnline: false,
                gender: 'male',
                hireDate: '28.03.2018',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 114,
                name: 'Diana Reed',
                team: 'Gunters',
                role: 'Frontend Developer',
                gmail: 'dianareed@gmail.com',
                birthday: '09.03.1987',
                age: 33,
                telegram: '@dianareed',
                lastLogin: '04.04.2022',
                isOnline: true,
                gender: 'female',
                hireDate: '22.10.2016',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 115,
                name: 'Ethan King',
                team: 'Gunters',
                role: 'QA Engineer',
                gmail: 'ethanking@gmail.com',
                birthday: '17.08.1995',
                age: 25,
                telegram: '@ethanking',
                lastLogin: '27.05.2022',
                isOnline: true,
                gender: 'male',
                hireDate: '14.12.2020',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 116,
                name: 'Fiona Hill',
                team: 'Gunters',
                role: 'UI/UX Designer',
                gmail: 'fionahill@gmail.com',
                birthday: '23.02.1993',
                age: 27,
                telegram: '@fionahill',
                lastLogin: '08.09.2021',
                isOnline: false,
                gender: 'female',
                hireDate: '30.04.2019',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 117,
                name: 'George Clark',
                team: 'Gunters',
                role: 'Backend Developer',
                gmail: 'georgeclark@gmail.com',
                birthday: '12.11.1986',
                age: 34,
                telegram: '@georgeclark',
                lastLogin: '10.07.2022',
                isOnline: false,
                gender: 'male',
                hireDate: '05.02.2018',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 118,
                name: 'Hannah Baker',
                team: 'Gunters',
                role: 'Frontend Developer',
                gmail: 'hannahbaker@gmail.com',
                birthday: '30.04.1991',
                age: 29,
                telegram: '@hannahbaker',
                lastLogin: '23.11.2021',
                isOnline: true,
                gender: 'female',
                hireDate: '17.08.2017',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 119,
                name: 'Ian Miller',
                team: 'Gunters',
                role: 'SEO Specialist',
                gmail: 'ianmiller@gmail.com',
                birthday: '14.09.1984',
                age: 36,
                telegram: '@ianmiller',
                lastLogin: '12.01.2022',
                isOnline: false,
                gender: 'male',
                hireDate: '09.04.2020',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            },
            {
                id: 120,
                name: 'Jasmine Reed',
                team: 'Gunters',
                role: 'Project Manager',
                gmail: 'jasminereed@gmail.com',
                birthday: '03.02.1988',
                age: 32,
                telegram: '@jasminereed',
                lastLogin: '30.06.2022',
                isOnline: true,
                gender: 'female',
                hireDate: '27.02.2016',
                avatar: 'https://insight-webstudio.ru/files_for_another_projects/avatar_1.png',
            }
        ],
        usersByPage: 9,
        currentPage: 1,
    },
    getters: {
        sortedUsers(state) {
            if (state.isSortDescending) {
                return [...state.users].sort((user1, user2) => user1[state.sortOption]?.localeCompare(user2[state.sortOption]))
            }

            return [...state.users].sort((user1, user2) => user2[state.sortOption]?.localeCompare(user1[state.sortOption]))
        },
        sortedAndSearchedUsers(state, getters) {
            if (state.searchField && state.searchQuery) {
                return getters.sortedUsers.filter(user => user[state.searchField].toLowerCase().includes(state.searchQuery))
            }
            return getters.sortedUsers        
        },
        maxPage(state) {
            return Math.ceil(state.users.length / state.usersByPage)
        },
    },
    mutations: {
        setIsSortDescending(state, bool) {
            state.isSortDescending = bool;
        },
        setSortOption(state, option) {
            state.sortOption = option
        },
        setSearchQuery(state, query) {
            state.searchQuery = query
        },
        setSearchField(state, fieldName) {
            state.searchField = fieldName
        },
        addUser(state, newUser) {
            state.users.push(newUser)
        },
        setIsAddUser(state, bool) {
            state.isAddUser = bool
        },
        setIsEditUser(state, bool) {
            state.isEditUser = bool
        },
        setEditedUser(state, user) {
            state.editedUser = user
        },
        replaceUser(state, editedUser) {
            const replacedUserIndex = state.users.findIndex(user => user.id === editedUser.id)

            state.users.splice(replacedUserIndex, 1, editedUser)
        },
        deleteUser(state, deletedUserId) {
            const deletedUserIndex = state.users.findIndex(user => user.id === deletedUserId)

            state.users.splice(deletedUserIndex, 1)
        },
        setCurrentPage(state, pageNumber) {
            state.currentPage = pageNumber
        },
        decreaseCurrentPage(state) {
            if (state.currentPage > 1) state.currentPage--
        },

    },
    actions: {
        increaseCurrentPage(context) {
            if (context.state.currentPage < context.getters.maxPage) context.state.currentPage++           
        },
        // async getPosts({state, commit}) {
        //     commit('setPage', 1)
        //     try {
        //         commit('setPostsLoading', true)
        //         const response = await axios.get(
        //             state.serverURL, {
        //                 params: {
        //                     _sort: 'date,id',
        //                     _order: 'desc,desc',
        //                     _page: state.page,
        //                     _per_page: state.limit
        //                 }
        //             }
        //         )
        //         commit( 'setTotalPages', Math.ceil(response.headers['x-total-count'] / state.limit))
        //         commit('setPosts', response.data)
        //     } catch (error) {
        //         console.log(error.message)
        //     } finally {
        //         commit('setPostsLoading', false)
        //     }
        // },

    },
    namespaced: true,
}